### ISSUE TITLE
Crashed when breaking Tinkers Construct - Tool Station

### ISSUE THREAD

**Issue by mjctechguy** [DoughnutServers/DonutCraftATL#14] opened 2016-08-04 09:29 UTC
Playing on Official Dountcraft Server version 0.1.0b

FML Log: https://gist.github.com/b393ac78b6bed3c3835a4961c65cbc86

Seems another user has had the issues as well..

**Comment by mrwindypops** [comment] 2016-08-04 12:16
Same issue on private server, Pack version 0.1.0b
Attempted to break tool station with stone axe. Client crashed to desktop, no errors in the server log.

ATL Console Log: https://gist.github.com/mrwindypops/eb34f7565c5ccf829f21144132dbfa53
Crash Report: https://gist.github.com/mrwindypops/45fd8680b4c44ba42f6779572e0e78ea

**Comment by DoughnutDev** [comment] 2016-08-04 14:52
Can you please post the crash report and not the log.

**Comment by mjctechguy** [comment] 2016-08-04 17:32
Here https://gist.github.com/mjctechguy/d1db0dd68d309c02117aecbce35f5d20

**Comment by DoughnutDev** [comment] 2016-08-04 20:33
Hi,

Are you using anything from ArchitectureCraft?

**Comment by mrwindypops** [comment] 2016-08-04 22:25
Not at the moment, this happened within about an hour of starting the server up, so not progressed in any mod really yet.

**Comment by DoughnutDev** [comment] 2016-08-04 23:46
Have you tried to generate a new world. Are you using BOP or Vanilla World
Gen? Are you using the configs given and the mods given or did you change
them?

**Comment by mrwindypops** [comment] 2016-08-05 15:23
New world with default world gen: Crashes.
New world with BOP world gen:  Crashes.

Both with standard configs and mods. Nothing added or removed.
I've not changed anything client side either.

Thanks for looking into this.

**Comment by DoughnutDev** [comment] 2016-08-05 16:05
Okay so I think the issue is the Forge version. So next update we will update and see.

**Comment by DoughnutDev** [comment] 2016-08-09 00:45
Should be fixed

**Closed by DoughnutDev** 2016-08-09 00:45 UTC
