### ISSUE TITLE
Eating food causes a minor crash.

### ISSUE THREAD

**Issue by sstarnes3** [DoughnutServers/DonutCraftATL#37] opened 2016-09-13 23:46 UTC
Not sure what to call this but it essentially kicks you from the server. The food gets eaten but no hunger is restored essentially wasting the food. I've only tested this with pam's harvestcraft foods so I do not know the extent of this bug.

Also, the spice of life overlay on the player's ui is missing. Like when you have a piece of food in your hand, it's supposed to say how much hunger and saturation you'll restore by eating that food. But it doesn't. However, mousing over the food items still shows the hunger and saturation amounts.

If you eat a the last piece of food in a stack you will get this weird 0 stack item. Which is the food you tried to eat but with a little zero by the icon. Using or selecting this item will remove it from your inventory.

If I were to take a guess I would think that it is related to a mod being updated in some way or a config file being reset. Possibly tough as nails. I know that mod adds thirst and temperature, maybe it also affects hunger and that is conflicting with spice of life and so it's causing 'crashes'.

**Comment by N00bK1ng** [comment] 2016-09-14 00:29
cooked mutton also causes a crash

**Comment by Kuroomega** [comment] 2016-09-15 04:32
This appears to be caused by the Hardcore Hunger feature in Better With Mods.
According to Eb on the Discord server, this resolved it.
I have since tested this in SP, and also found it to resolve. Turned it back on, and the crash returned in SP.

**Comment by pathways029** [comment] 2016-09-15 10:49
https://github.com/BeetoGuy/BetterWithMods/issues/32

https://github.com/squeek502/SpiceOfLife/issues/102

**Comment by DoughnutDev** [comment] 2016-09-15 21:30
Fixed in 2.0.0-005

**Closed by DoughnutDev** 2016-09-15 21:30 UTC
